version: '3'
services:
  db:
    platform: linux/amd64
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
     - ${POSTGRES_PORT}:5432
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data